### PR TITLE
Adding samples for Aruba Central REST APIs and Streaming APIs

### PR DESCRIPTION
**Pull request by karthikeyan-dhandapani**

### CODE REVIEW

**Comment by keplerk** [comment]
Hopping to see this commit merged, I've looking for streaming apis examples since the latest central update. 🥂

**Comment by noorul** [comment]
I think we should make it a library and publish it to pypi.

**Comment by karthikeyan-dhandapani** [comment]
> I think we should make it a library and publish it to pypi.

Hi Noorul,

Publishing to PyPi is a good suggestion. But it helps to have working samples in GitHub, for someone to look at it as reference if they want to develop in another programming language and also use this to try / demonstrate streaming APIs and REST APIs. 

Thanks,
Karthik

**Comment by keplerk** [comment]
> > I think we should make it a library and publish it to pypi.
> 
> Hi Noorul,
> 
> Publishing to PyPi is a good suggestion. But it helps to have working samples in GitHub, for someone to look at it as reference if they want to develop in another programming language and also use this to try / demonstrate streaming APIs and REST APIs.
> 
> Thanks,
> Karthik

Indeed i work with NodeJs so having a library for python wont help me too much but having examples does.

**Comment by karthikeyan-dhandapani** [comment]
@noorul Could you accept the merge if you do not have further queries?

**Comment by noorul** [comment]
I think @timcappalli  provided you access to merge this code.

I would like to see this comply with https://www.python.org/dev/peps/pep-0008/

**Comment by keplerk** [comment]
Thanks for the merge @noorul !! 
Time to port it to NodeJs

Regards.

**Comment by karthikeyan-dhandapani** [comment]
@noorul Thank you for the review!

**Pull request merged**
