### PR TITLE
PEP8 changes and add geolocation to sites

### PR DESCRIPTION
**Pull request by karthikeyan-dhandapani**
- Updated the REST API based python scripts to PEP8 standard
- Added geolocation configuration option to createSites function

### CODE REVIEW

**Comment by karthikeyan-dhandapani** [comment]
@noorul please help!

**Comment by noorul** [comment]
How do we know that this is working code? Can you write tests?

**Comment by keplerk** [comment]
Agree with @noorul , i think any pull request must include its own tests before merging

**Comment by karthikeyan-dhandapani** [comment]
@noorul and @keplerk agree! I was thinking about it as well. Currently, the unit tests are commented out in main function. Will formulate a proper test case and add another commit. Thanks!

**Comment by noorul** [comment]
@karthikeyan-dhandapani  I would wait for unit test to be commented out and made it part of travis-ci so that I am sure that the code that I am merging is working code.

**Comment by alagoutte** [comment]
Also it will be a good idea to split the patch in 2 (one for PEP8 fix) and another for add geolocation stuff (it is complicated to look diff)

**Comment by keplerk** [comment]
The geolocation @alagoutte it's just adding a second object to the site request, but i agree with you, this pull request could be granular, that means one thing at the time.

**Comment by karthikeyan-dhandapani** [comment]
@alagoutte and @keplerk Thanks for the feedback. Splitting the commit now seems to be a big process. I will follow it next time, unless someone can guide me easy way to split commits. 

@noorul , To run automated tests upon commit, tests need Aruba Central Instance with credentials. How should I manage to run those tests without providing the credentials in travis.yml file and uploading it in GitHub? Should I just write a test using pytest and share you the test cases and result?

**Comment by karthikeyan-dhandapani** [comment]
Also there are multiple projects in the repo. Does Travis-Ci work on a specific folder inside the repo?

**Comment by keplerk** [comment]
@karthikeyan-dhandapani Maybe you could create an isolated tenant on an isolated msp ?
Or just leave the template for someone to manually run the tests with their own central credentials ?

**Comment by noorul** [comment]
I think unit tests can be run on travis

**Comment by noorul** [comment]
For functional tests maybe Jenkins can be used

**Pull request merged**
